// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xeknezvdtjynpraojztk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhla25lenZkdGp5bnByYW9qenRrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkzMDkxMjAsImV4cCI6MjA2NDg4NTEyMH0.6w4DdtrTVZoR7Q7lL48fYGRMCtWHjKddQ_5goSXBNfo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);